[option]
exclude_paths = ["src/cmn/*"]
indent = 2
textwidth = 120

[textrules]
style_directives = true
style_textwidth = true
style_semicolon = true

[syntaxrules]
style_operator_integer_leading_space = true
uppercamelcase_module = true
uppercamelcase_package = true
tab_character = true
style_indent = true
style_operator_arithmetic = true
style_operator_boolean = true
style_operator_integer = true
style_operator_unary = true
style_operator_arithmetic_leading_space = true
style_operator_boolean_leading_space = true
style_keyword_0or1space = true
style_keyword_0space = true
style_keyword_1or2space = true
style_keyword_1space = true
style_keyword_construct = true
style_keyword_datatype = false                 # Overly restrictive.
style_keyword_end = true
style_keyword_maybelabel = true
style_keyword_new = true
style_keyword_newline = true
style_commaleading = false
eventlist_or = true
blocking_assignment_in_always_ff = true
non_blocking_assignment_in_always_comb = true
enum_with_type = true
keyword_forbidden_priority = true
keyword_forbidden_unique = true
keyword_forbidden_unique0 = true
action_block_with_side_effect = true
default_nettype_none = true
function_same_as_system_function = true
keyword_forbidden_wire_reg = true
non_ansi_module = true
localparam_type_twostate = true
parameter_type_twostate = true
localparam_explicit_type = true
parameter_explicit_type = true
parameter_default_value = true
parameter_in_generate = true
parameter_in_package = true
genvar_declaration_in_loop = true
genvar_declaration_out_loop = false
keyword_forbidden_generate = true
keyword_required_generate = false
multiline_for_begin = true
multiline_if_begin = true
inout_with_tri = true
input_with_var = false                         # Currently set to false until more discussion
output_with_var = false                        # Currently set to false until more discussion
interface_port_with_modport = true
blocking_assignment_in_always_latch = true
case_default = true
function_with_automatic = true
level_sensitive_always = true
operator_case_equality = true
keyword_forbidden_always = true
generate_case_with_label = true
generate_for_with_label = true
generate_if_with_label = true
explicit_case_default = true
explicit_if_else = true
loop_statement_in_always_comb = true
loop_statement_in_always_ff = true
loop_statement_in_always_latch = true
